# Site settings
title: Anomalous Technologies
description: Anomalous Technologies Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: https://www.anomaloustech.co.za
# User settings
username: Anomalous Technologies
user_description: Site under construction.
user_title: Finding the needle in data haystacks
email: christo@anomaloustech.co.za
twitter_username: anomaloustech
github_username:  anomaloustech

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
